version: '3.8'

services:
  auth-service:
    build: 
      context: ./backend/AuthService
    ports:
      - "7223:7223"
    volumes:
      - ./backend/data/auth.db:/data/auth.db
    networks:
      - app-network

  product-service:
    build: 
      context: ./backend/ProductService
    ports: 
      - "7224:7224"
    volumes:
      - ./backend/data/products.db:/data/products.db
    depends_on:
      - auth-service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge